version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: StrongPassword123
      POSTGRES_DB: testy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8787:8787"
    environment:
      DATABASE_URL: postgresql://postgres:StrongPassword123@db:5432/testy

volumes:
  pgdata: